# Generated by Django 5.1.4 on 2024-12-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='x',
        ),
    ]
